// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutsourceTracker.Data;

#nullable disable

namespace OutsourceTracker.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20260319042149_ZoneUpdate")]
    partial class ZoneUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("OutsourceTracker.Models.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessAccounts");
                });

            modelBuilder.Entity("OutsourceTracker.Models.Trailers.Trailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LocatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Location")
                        .HasColumnType("BLOB");

                    b.Property<double?>("LocationAccuracy")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .IsDescending();

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("OutsourceTracker.Models.Zones.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Boundry")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockPoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryPoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitPoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("OutsourceTracker.Models.Trailers.Trailer", b =>
                {
                    b.HasOne("OutsourceTracker.Models.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
