// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutsourceTracker.Data;

#nullable disable

namespace OutsourceTracker.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20260205070722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OutsourceTracker.Models.Trailers.CommercialTrailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpottedAccuracy")
                        .HasColumnType("REAL");

                    b.Property<string>("SpottedBy")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpottedLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("SpottedLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("SpottedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Trailers");
                });
#pragma warning restore 612, 618
        }
    }
}
