<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c1f464e5-004a-4827-9267-4b08dc9ded30</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Backend", ""))</RootNamespace>
	<IsPackable>true</IsPackable>
	<InvariantGlobalization>true</InvariantGlobalization>
	<ApplicationIcon>outsource.ico</ApplicationIcon>
    <Title>OutsourceTacker Common</Title>
    <Authors>Austin Vandersluis</Authors>
    <Description>RESTful API backend — a platform for outsourcing work management and trailer/asset tracking in logistics and transportation.</Description>
    <Copyright>Copyright © $([System.DateTime]::Now.Year) $(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/OutsourceTracker/</PackageProjectUrl>
    <PackageIcon>package_icon.jpg</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/OutsourceTracker/OutsourceTracker.Backend</RepositoryUrl>
    <PackageTags>logistics;trailer-tracking;outsourcing;work-management;transportation;common;utilities;interfaces</PackageTags>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="SendGrid.Extensions.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="outsource.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OutsourceTracker.Common\src\OutsourceTracker.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="package_icon.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
